settingBox:
  title: Language and Color
  selection:
    lang:
      title: Select Language
      german: German
      de_DE: German
      english: English
      en_US: English
    color:
      title: Color scheme
      google: Google
      codefrog: CodeFrog
      dark: Dark
