settingBox:
  title: Spache und Farbe
  selection:
    lang:
      title: Sprache wählen
      german: Deutsch
      de_DE: Deutsch
      english: Englisch
      en_US: Englisch
    color:
      title: Farbschema
      google: Google
      codefrog: CodeFrog
      dark: Dunkel
